# DB
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/abel
    username: sa
    password:
    driver-class-name: org.h2.Driver

# JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# Session
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: localhost
    port: 6379

# Log
logging.level:
  org.hibernate.SQL: debug